### ISSUE TITLE
ขายวงเงินหลัก 150000 บาท แถม Botox50U แล้วหน้าจัดการยอดขาย ไม่ขึ้นยอดวงเงิน

### ISSUE THREAD

**Issue by satawat-t** [satawat-t/kkc#1]
https://www.kkcpos.com/pos-system/course/sale

table : credit_sale_types

- ขายวงเงินหลัก 150000 บาท  แถม Botox 50หน่วย  ในหน้าจัดการยอดขาย ขึ้นแค่รายการของ Botox ครับ
![image](https://user-images.githubusercontent.com/60998712/88033633-cbd59c00-cb69-11ea-956e-3c1d58e340d3.png)

- รายการใบเสร็จแรก จะต้องมียอด 150000 บาทให้แบ่งยอดด้วย
![image](https://user-images.githubusercontent.com/60998712/88036191-6be0f480-cb6d-11ea-8375-fbf2eeaa1b06.png)

**Comment by troyzayne** [comment]
Sun

**Comment by IbanezHcu** [comment]
ทำการ Test แล้วยังพบปัญหาเดิมครับ  คือ ในหน้าจัดการยอดขาย ไม่มีรายการ ขายวงเงิน 150000 บาท ให้แบ่งยอด 
ตรวจสอบ Table   credit_sale_histories เพื่อดูประวัติของวงเงิน พบว่ามีประวัติวงเงิน 150000 เกิดขึ้นจริง และลูกค้าได้วงเงินจริง 

![image](https://user-images.githubusercontent.com/69230636/89509892-1148c900-d7fa-11ea-9ec2-986c0df32823.png)

**Comment by IbanezHcu** [comment]
[ข้อ8. ขายวงเงินหลัก 150000 บาท แถม Botox50U แล้วหน้าจัดการยอดขาย ไม่ขึ้นยอดวงเงิน #1.docx](https://github.com/satawat-t/kkc/files/5050071/8.150000.Botox50U.1.docx)

**Comment by IbanezHcu** [comment]
ข้อ 8 
#1 ขายวงเงินหลัก 150000 บาท แถม Botox50U แล้วหน้าจัดการยอดขาย ไม่ขึ้นยอดวงเงิน ** หน้าจัดการ ในส่วนของวงเงิน 150000 ยังไม่ขึ้น   ขึ้นมาแค่ส่วนที่แถม Botox 

 
![image](https://user-images.githubusercontent.com/69230636/89770683-4ec69280-db29-11ea-8229-6488a945aeaf.png)


Test แล้วในส่วนของวงเงิน ยังไม่ขึ้นมาให้แบ่งยอดครับ  ขึ้นมาแค่ส่วนของตัวที่แถมครับ
