### ISSUE TITLE
รายงานตรวจสอบยอดขาย ไม่ต้องโชว์ยอดเงินบางรายการ

### ISSUE THREAD

**Issue by satawat-t** [satawat-t/kkc#10]
https://www.kkcpos.com/report/sale-payment

table : sale_payments

- ไม่ต้องแสดงรายการที่ payment_machine_id = 4,18,19,21,23,26,27,28 (ยอดใน Excel ก็จะไม่แสดงรายการนี้เหมือนกันครับ)
- สำนักงานใหญ่ สามารถฟิลเตอร์และ export excel ได้ทุกสาขา  สาขาอื่นๆจะดูได้แค่สาขาตัวเองที่ Login

**Comment by troyzayne** [comment]
Big
