### ISSUE TITLE
ในหน้าขายคอร์ส เงื่อนไขการคิดวงเงินถาดแถม

### ISSUE THREAD

**Issue by satawat-t** [satawat-t/kkc#11]
https://www.kkcpos.com/pos-system/course/sale

จำนวนวงเงินถาดแถมของลูกค้าคือ customers.giftset_credit_amount
table ที่เก็บ transaction วงเงินถาดแถม credit_sale_histories

** เงื่อนไขตอนแรกที่ได้มาจาก User คือ 50% จากยอดการชำระ จะถูกนำมาเป็นวงเงินถาดแถมให้ลูกค้า

เว้นกรณีที่ขายคอร์ส Buffet ทุกตัว จะต้องไม่นำมาคำณวนวงเงินถาดแถมให้ลูกค้าครับ
เช่น KKC Pack 1 มูลค่า 49900 บาท ลูกค้าจะได้วงเงินถาดแถม = 0

กรณีขายวงเงินทุกชนิด จะไม่ถูกนำไปคำณวนเป็นวงเงินถาดแถมให้ลูกค้า ยกเว้นวงเงินมัดจำล่วงหน้า (credit_sale_types.type = advance) ที่สามารถให้วงเงินถาดแถมกับลูกค้าได้

กรณีขายสินค้าทุกชนิด จะไม่ถูกนำไปคำณวนเป็นวงเงินถาดแถมให้ลูกค้า

**Comment by troyzayne** [comment]
Sun
