### ISSUE TITLE
รายงานออดิต + รายงานออดิตขายสินค้า

### ISSUE THREAD

**Issue by satawat-t** [satawat-t/kkc#12]
https://www.kkcpos.com/report/audit

table : contracts , sale_payments

- มูลค่าสัญญา คือ มูลค่าเต็มของสัญญานั้น เช่นคอร์ส A ราคา 5000 บาท , คอร์ส B ราคา 7000 บาท มูลค่าสัญญา = 12000 บาท
  ถ้าลูกค้าชำระไม่ครบแล้วยังมีค้างชำระ มูลค่าสัญญาจะเป็น 12000 บาท เหมือนกันครับ
- ตัวเลขไม่เอาทศนิยม
- ครั้ง คือจำนวนที่ลูกค้าซื้อคอร์ส จำนวนนี้จะไม่ลดลง
- ราคา/ครั้ง
- จำนวนทั้งสิ้นคือราคาของคอร์สนั้นที่ลูกค้าซื้อมา (อาจจะไม่ใช่ราคาปกติ เพราะหน้าร้านจะเปลี่ยนราคาได้)
- เฉพาะคอร์สที่เป็น Buffet จะแสดงแค่ชื่อบุฟเฟ่ต์ ไม่แสดงคอร์สย่อย (ใน Excel ก็แสดงแค่ชื่อบุฟเฟ่ต์)

รายงานขายสินค้า
- รูปแบบจะคล้ายๆกับคอร์สครับ แต่เป็นในรูปแบบสินค้า

**Comment by satawat-t** [comment]
ประเภทการชำระ ถ้าเป็นเงินสด บัตรเดรดิต หรืออื่นๆที่ไม่ใช่วงเงิน ให้แสดงเป็น **ทั่วไป**
ถ้า sale_payments.use_credit_payment มีค่าเท่ากับรายการด้านล่าง
advance_credit_amount = วงเงินมัดจำล่วงหน้า
primary_credit_amount = วงเงินหลัก
cutdown_credit_amount = วงเงินคัตดาวน์
second_credit_amount = วงเงินแถมโปรโมชั่น

**contracts.buffet** = 777  คือคอร์สโปรโมชั่น   ,  888 คือคอร์สแพคเกจ ต้องแสดงรายชื่อคอร์สย่อยทั้งหมด
**contracts.buffet** = 999 คือคอร์สบุฟเฟ่ต์ ไม่ต้องแสดงคอร์สย่อย และจำนวนครั้ง

**มูลค่าสัญญา** : courses.total_price
**ครั้ง** : contracts.amount
**ราคา/ครั้ง** : contracts.price
**จำนวนทั้งสิ้น** : contracts.raw_amount

// รายงานออดิตขายสินค้า    where ด้วย contracts.type_contract = product
**วันที่ขายสินค้า** : contracts.created_at
**รหัสลูกค้า** : contracts.customer_id
**ชื่อ-สกุล** : customers.name_th
**เลขที่เอกสาร** : stock_transactions.number
**รายการ** : contracts.treatment_name
**จำนวน** : contracts.amount
**ราคาต่อหน่วย** : contracts.price
**ส่วนลด** : contracts.discount
**ยอดรวม** : contracts.raw_amount
**ประเภทการชำระ** ตามด้านบนครับ

**Comment by satawat-t** [comment]
- วิดีโอรายละเอียดที่ zoom กันนะครับ
https://drive.google.com/drive/folders/1B4_uV8Db9DKUzkHzizX2TmFcCeHEpWnN?usp=sharing

**Comment by satawat-t** [comment]
- มีแก้ไขครับ ช่อง มูลค่าสัญญา เปลี่ยนการดึงค่า ไปดึงที่ courses.total_price (จากเดิมดึงที่ already_price)
- contracts.buffet = 999.00 ให้แสดงแค่ชื่อคอร์สเพียง row เดียวครับ
- ประเภทสัญญาใน Filter หน้าเว็บจะมี "อัพเกรดสัญญา" ให้ where ด้วย courses.upcourse ถ้าไม่เท่ากับ 0 คือเป็นการอัพเกรดสัญญาครับ
- ผมลอง Filter สัญญาถาดแถม วันที่ค้นหาคือ 30-30 ในรายงานแสดงวันที่เริ่มสัญญาของปี 2019 ติดมาด้วยครับ
![image](https://user-images.githubusercontent.com/60998712/88906875-2796d800-d282-11ea-9559-a1da7cd6651b.png)

- บางรายการแสดงจำนวนครั้งเป็น 0 ครั้ง
![image](https://user-images.githubusercontent.com/60998712/89021835-5b8a0000-d34b-11ea-934a-75f7bbcf6610.png)

**Comment by troyzayne** [comment]
big
