### ISSUE TITLE
รายงานแบ่งยอดแต่ละสาขา

### ISSUE THREAD

**Issue by satawat-t** [satawat-t/kkc#13]
https://www.kkcpos.com/report/branch-commission

Table การชำระ : sale_payments , table แบ่งยอดสาขา : commission_branch , table ยอดหักเข้าออฟฟิศ : commission_fees

รายงานนี้ทุกสาขาเข้าดูได้หมดครับ เพราะจะค้นหาจากรหัสลูกค้า ว่าลูกค้าเข้าไปใช้บริการที่สาขาไหน และแบ่งยอดให้สาขาไหนบ้าง 
อย่างเช่น ขายคอร์ส Filler CC ราคา 22000 บาท ลูกค้าชื่อ A ทำการขายโดยสำนักงานใหญ่
1.ทำการแบ่งยอดให้สาขาสำนักงานใหญ่ 50% มูลค่า 11000 บาท
2.ทำการแบ่งยอดให้สาขาทองหล่อ 50% มูลค่า 11000 บาท
3.หักค่าธรรมเนียมหรือหักเข้าออฟฟิศในหน้าจัดการยอดขายสำหรับ Filler CC จำนวน 2000 บาท
เมื่อค้นหาลูกค้า A ในรายงานจะแสดงเป็น
เลขที่ใบเสร็จ วันที่ออกใบเสร็จ ทรีตเม้นท์ ยอดชำระ ยอดหักเข้าออฟฟิศ ยอดสุทธิ ยอดจากสาขา ยอดเข้าสาขา ยอดสาขา
RE11111111111 | 2020-07-20 | Filler CC | 11000 | 1000 | 10000 | สำนักงานใหญ่ | สำนักงานใหญ่ | 10000
RE11111111111 | 2020-07-20 | Filler CC | 11000 | 1000 | 10000 | สำนักงานใหญ่ | ทองหล่อ | 10000

รูปแบบ excel ไม่เหมือนบนเว็บครับ
** แก้ไขชื่อคอลั่ม ยอดสุทธิช่องสุดท้าย เป็นยอดสาขา

** สิ่งที่ยังผิดในรายงานนี้
รายงานนี้จะค้นหาจากรหัสลูกค้า  เปิดรายงาน Default ให้ไม่แสดงข้อมูลในตารางเลยครับ จนกว่าจะมีการค้นหาลูกค้า
- รายงานนี้ที่ผิดจะคล้ายๆกับรายงานสรุปยอดขายสาขา ขายคอร์สราคา 22000 บาท แบ่งยอดให้สำนักงานใหญ่ กับ ทองหล่อ แต่ระบบไม่แสดงรายการแบ่งยอดให้ทองหล่อ แต่ยอดชำระกลับรวมเป็น 22000 บาท ที่สาขาสำนักงานใหญ่ ตามตัวอย่างที่ผมเขียนให้ด้านบนคือถูกต้อง
- การคำณวนยอดหักเข้าออฟฟิศจะเหมือนกับที่ทำไปในหน้าสรุปยอดขายสาขา issue #5  #9

**Comment by troyzayne** [comment]
นัท

**Comment by satawat-t** [comment]
sale_payments.deleted_at ถ้ามีค่า ไม่เอาข้อมูลมาแสดง เพราะใบเสร็จถูกลบไปแล้ว
