### ISSUE TITLE
หน้าจัดการยอดขาย มีการแบ่งยอดเกินมูลค่าคอร์ส , ไม่สามารถคำณวน % แบบย้อนกลับ , ไม่สามารถลบรายการแบ่งยอดได้

### ISSUE THREAD

**Issue by satawat-t** [satawat-t/kkc#15]
https://www.kkcpos.com/transaction/sales

table แบ่งยอดเซลล์ : commission_sales , table แบ่งยอดสาขา : commission_branch , table : หักค่าธรรมเนียม : commission_fees
table ใบเสร็จรับเงิน : sale_payments

- ขายคอร์ส 2 ตัวใน 1 สัญญา
ทำให้แบ่งยอดให้ 2 สาขา ตามภาพ แต่ระบบยอมให้ใส่มูลค่าแบ่งยอด เกินกว่ามูลค่าจริงของคอร์สครับ ต้องมีโค้ดดักไว้ไม่ให้บันทึกด้วยครับ
![image](https://user-images.githubusercontent.com/60998712/88448456-71d61e80-ce68-11ea-9742-0c8fcf262982.png)
**- การหักค่าธรรมเนียม และ แบ่งยอดเซลล์ ก็ไม่ให้แบ่งยอดเกินมูลค่าของคอร์สครับ**
![image](https://user-images.githubusercontent.com/60998712/88448524-15bfca00-ce69-11ea-80e0-26678f031a8e.png)

- กรณีที่ใส่จำนวนเงิน ให้ระบบคำณวนจำนวน % ให้ด้วยครับ ว่าคิดว่าเป็นกี่ % 
   การคำณวนของหน้านี้ จะมีแต่การหักค่าธรรมเนียม ที่คำณวนมูลค่าจากยอดเงินคงเหลือ / แบ่งยอดสาขา กับ เซลล์ จะคำณวนจาก ยอดเงินก่อนหัก
![image](https://user-images.githubusercontent.com/60998712/88448644-26247480-ce6a-11ea-95dd-226a46abe179.png)

- ทำการแบ่งยอดทั้ง 3 ประเภทไป และกดบันทึก  หลังจากนั้น ทำการลบรายการที่แบ่งไป แล้วไม่สามารถกดบันทึกได้
![image](https://user-images.githubusercontent.com/60998712/88448630-02612e80-ce6a-11ea-8dcb-2f827f3d8d0d.png)

- ทำการขายสินค้า 3 ตัว สามารถหักค่าธรรมเนียมได้  แต่จะแบ่งยอดสาขา กับ ยอดเซลล์ ยอดเงินจะขึ้น 0 ครับ
![image](https://user-images.githubusercontent.com/60998712/88448699-a8149d80-ce6a-11ea-82a9-0ce1735486b5.png)

![image](https://user-images.githubusercontent.com/60998712/88448733-f75ace00-ce6a-11ea-98d4-3f6cd52c987a.png)

**Comment by troyzayne** [comment]
ซัน

**Comment by satawat-t** [comment]
issue 39 น่าจะได้รับผลกระทบจากการแก้ issue นี้
https://github.com/satawat-t/kkc/issues/39
