### ISSUE TITLE
หน้าตัดคอร์ส ถ้าไม่เลือกค่ามือพนักงานให้ตัดคอร์สไม่ได้ ,ในส่วนของประวัติการตัดใช้ สามารถค้นหาวันที่ได้

### ISSUE THREAD

**Issue by satawat-t** [satawat-t/kkc#16]
https://www.kkcpos.com/pos-system/course/cut/

table ค่ามือ : commissions , ค่ามือที่ผูกคอมมิชชั่น treatment_commission
table พนักงาน : staff

- หน้าตัดคอร์ส ถ้ายังไม่เลือกค่ามือ ต้องมี pop-up แจ้งเตือน User
  ตัวอย่างตามภาพ ค่ามือ D=5,TP=20,N=15 (ค่ามือหมอ 5 หน่วย,เทอราปิส 20 หน่วย,พยาบาล 15 หน่วย)
  หาก User เลือกพนักงานที่เกี่ยวข้องกับค่ามือไม่ครบ ให้แจ้งเตือน และไม่อนุญาตให้ตัดคอร์ส
- ทำสถานะหลังคำว่าจัดการแพทย์และตำแหน่งอื่น กรณีที่มีการเลือกพนักงาน เช่น จัดการแพทย์(1) ถ้าเลือก 2 ตำแหน่ง จัดการแพทย์(2)
   เพื่อให้ User รู้ว่าได้เลือกค่ามือพนักงานได้ตำแหน่งนี้ไปแล้ว เพราะ User จะทำการตัดคอร์สทีละหลายๆคอร์ส จะเกิดการสับสน
![image](https://user-images.githubusercontent.com/60998712/88448862-350c2680-ce6c-11ea-8511-dbb9e1f57035.png)

- ในหน้าประวัติการตัดใช้ ให้สามารถค้นหาข้อมูลวันที่ ที่ลูกค้าเข้ามาใช้บริการได้ (table : course_cut)
- คอลั่มเวลา เปลี่ยนชื่อเป็น "วันที่"
![image](https://user-images.githubusercontent.com/60998712/88448771-44d73b00-ce6b-11ea-832e-d7c9d23c5eb7.png)

- ในปุ่มจัดการเครื่องมือ ทำรูปแบบให้เหมือน ปุ่มจัดการสูตรยา มีการให้เหตุผลแค่ครั้งเดียว ไม่ว่าจะเพิ่มกี่เครื่องมือ
![image](https://user-images.githubusercontent.com/60998712/88449052-0727e180-ce6e-11ea-9b2f-e85c4770c4ab.png)

- ในหน้าจัดการสูตรยา ตอนนี้ต้องกดปุ่ม นำเข้าสูตรยาเดิม เพื่อตัดสูตรยาออกสต็อค ความจริงระบบต้องตัดคอร์สให้อัตโนมัติ แม้ไม่ได้กดปุ่ม 
   จัดการสูตรยา (User จะกดปุ่มจัดการสูตรยาก็ต่อเมื่อต้องการเปลี่ยนสูตรยา) table ตัวยา : treatment_commission
- แทปเพิ่มสูตรยา ช่องค้นหาสูตรยา User จะใช้เป็นรหัสตัวยาและชื่อ treatments.treatment_no และ treatments.name สองตัวนี้ในการค้นหา
   โปรแกรมเมอร์คนเก่าที่เขียนไว้ เค้าเขียนค้นหาแค่ชื่ออย่างเดียวครับ
![image](https://user-images.githubusercontent.com/60998712/88452312-d48ae280-ce87-11ea-9bfb-f652e2964bba.png)

- อีกกรณีที่เจอก็คือ ถ้า User ใส่สูตรยา แล้วกดเพิ่มสูตรยาในคอร์สไปแล้ว สต็อคจะถูกตัดออกตั้งแต่ตอนกดเพิ่มสูตรยา(ยังไม่กดปุ่มดำเนินการตัดคอร์ส)
แล้ว User กดปุ่มยกเลิกรายการ ตัวยาจะถูกตัดออกสต็อคไป ทั้งๆที่ยังไม่ได้ตัดคอร์สครับ ต้องตัดสต็อคตอนที่กด ดำเนินการตัดคอร์ส ครับ
![image](https://user-images.githubusercontent.com/60998712/87866611-17dbe180-c9ae-11ea-9376-f3c4214c4387.png)

**Comment by satawat-t** [comment]
กดเพิ่มในหน้าจัดการสูตรยา แล้วสต็อคไม่ลง (ถูกต้องแล้ว)
แต่ กดลบในหน้าสูตร สต็อคคืนค่ากลับเข้าระบบ ทำให้จำนวนสต็อคเพิ่มขึ้นมากกว่าความเป็นจริง

**Comment by troyzayne** [comment]
กิต ถึง ปุ่มจัดการเครื่องมือ

**Comment by troyzayne** [comment]
ซันหน้าสูตรยา

**Comment by satawat-t** [comment]
- วิดีโอ zoom ที่คุยกับกิตเรื่องหน้าตัดคอร์สครับ
https://drive.google.com/drive/folders/1DIslbC2xrHo6bSytg9UUOqqswin9Ppob?usp=sharing

**Comment by troyzayne** [comment]
คุยกับกุ้ง 7/8/20

1. ถ้าไม่จัดการ เทอราปิส จะกดดำเนินการตัดคอร์สไม่ได้ ต้องมี pop-up แจ้งเตือน User
2. .ในหน้าจัดการบุคลากร ไม่ต้อง show ตัวเลข ทำสถานะหลัง จัดการแพทย์และตำแหน่งอื่นให้เปลี่ยนสีเท่านั้น ไม่ต้องขึ้นตัวเลข
เพื่อให้ User รู้ว่าได้เลือกค่ามือพนักงานได้ตำแหน่งนี้ไปแล้ว เพราะ User จะทำการตัดคอร์สทีละหลายๆคอร์ส จะเกิดการสับสน

**Comment by IbanezHcu** [comment]
[ข้อ5 . หน้าตัดคอร์ส ถ้าไม่เลือกค่ามือพนักงานให้ตัดคอร์สไม่ได้ ,ในส่วนของประวัติการตัดใช้ สามารถค้นหาวันที่ได้ #16.docx](https://github.com/satawat-t/kkc/files/5050013/5.16.docx)

**Comment by IbanezHcu** [comment]
ข้อ 5
#16 หน้าตัดคอร์ส ถ้าไม่เลือกค่ามือพนักงาน ให้ตัดคอร์สไม่ได้, และในส่วนของประวัติการตัดใช้สามารถค้นหาวันที่ได้ 
** ถ้าไม่เลือกค่าหัตถการ จะขึ้น error ** ถูกต้องแล้ว
 
![image](https://user-images.githubusercontent.com/69230636/89770330-cea02d00-db28-11ea-9536-3d4a007846b2.png)

ทำสถานะหลังคำว่าจัดการแพทย์และตำแหน่งอื่น กรณีที่มีการเลือกพนักงาน เช่น จัดการแพทย์(1) ถ้าเลือก 2 ตำแหน่ง จัดการแพทย์(2)  เพื่อให้ User รู้ว่าได้เลือกค่ามือพนักงานได้ตำแหน่งนี้ไปแล้ว เพราะ User จะทำการตัดคอร์ส ทีละหลายๆคอร์ส จะเกิดการสับสน
** ยังไม่ถูกแก้ไข **
** ทำการเลือกแพทย์ 3 ท่าน และ พยาบาล 2 ท่าน **
![image](https://user-images.githubusercontent.com/69230636/89770373-e081d000-db28-11ea-9d7d-1df205b030a4.png)







ไม่ขึ้นสถานะ แพทย์ 1 , แพทย์2

![image](https://user-images.githubusercontent.com/69230636/89770444-fb544480-db28-11ea-8d52-660946f38643.png)


ในหน้าประวัติการตัดใช้ ให้สามารถค้นหาข้อมูลวันที่ ที่ลูกค้าเข้ามาใช้บริการได้
** ไม่สามารถ ค้นหาด้วยวันที่ได้ **
 
![image](https://user-images.githubusercontent.com/69230636/89770465-01e2bc00-db29-11ea-83fe-d728783ca38f.png)

ในปุ่มจัดการเครื่องมือ ทำรูปแบบให้เหมือน ปุ่มจัดการสูตรยา มีการให้เหตุผลแค่ครั้งเดียว ไม่ว่าจะเพิ่มกี่เครื่องมือ
** กดเพิ่มรายการทุกครั้ง ระบบบังคับให้ใส่เหตุผล ต้องการให้ขึ้นใส่เหตุผลแค่ครั้งเดียว เหมือนการจัดการสูตรยา**
 
![image](https://user-images.githubusercontent.com/69230636/89770494-0c9d5100-db29-11ea-96ae-9c4fa57e0b10.png)

**Comment by satawat-t** [comment]
- ในหน้าประวัติการตัดคอร์ส ของบุฟเฟ่ต์ แพคเกจ โปรโมชั่น ต้องมีให้ค้นหาวันที่เหมือนกับหน้าคอร์สปกติ
- UI หน้าเลือกค่ามือ กับ ตัวยา และเครื่องมือ ในหน้าตัดคอร์สบุฟเฟ่ต์ ให้เป็นแบบหน้าคอร์สปกติครับ (ตอนนี้ยังเป็นแบบเก่า)

**Comment by satawat-t** [comment]
- เลขที่สัญญา CCCLP020084918 มีการใช้งาน botox ได้ 200 หน่วย และชำระเต็มจำนวน
![image](https://user-images.githubusercontent.com/60998712/91515025-6caa3a80-e912-11ea-8ae1-11650c825c71.png)

![image](https://user-images.githubusercontent.com/60998712/91514900-25bc4500-e912-11ea-8c4f-97f05bc8475a.png)

- เมื่อกดเข้าไปในหน้าตัดคอร์ส ระบบให้ตัดได้แค่ 1 หน่วย
![image](https://user-images.githubusercontent.com/60998712/91514965-45ec0400-e912-11ea-9672-610f1c68585b.png)
