### ISSUE TITLE
รายงานสรุปการใช้ยาและการตัดคอร์ส

### ISSUE THREAD

**Issue by satawat-t** [satawat-t/kkc#17]
https://www.kkcpos.com/report/medicine-cut-cource

table : course_cuts , course_cut_medicines
           course_cut_doctors , course_cut_nurses , course_cut_therapist , course_cut_physical_therapist 

- คอลั่มคอร์ส แสดงรายชื่อคอร์สที่ลูกค้าตัดใช้งาน ไม่ว่าจะมีการตัดใช้ยาหรือไม่ ก็ต้องขึ้น    (contracts.treatment_name)
- คอลั่มรายการ ตัวยาที่ใช้ในการตัดคอร์ส     (course_cut_medicine.medicine_id) > join table : treatments.id
- จำนวนยาที่ใช้ในการตัดคอร์ส   (course_cut_medicines.qty)
- จำนวนครั้งที่ตัดใช้งานคอร์ส    (น่าจะ course_cuts.qty)
- จำนวนครั้งที่ใช้ได้ คือ จำนวนคอร์สที่ลูกค้าใช้ได้ทั้งหมดที่มี(ไม่ใช่ที่เหลือ) จำนวนนี้จะไม่ลดลง  (contracts.amount)
- ครั้งที่ทำ คือจำนวนครั้งที่ลูกค้าทำไปแล้ว   (contracts.used)

ประเภทการใช้งาน
- ไม่ต้องมีวงเล็บ (0.0000 บาท)  ให้แสดงเป็นชื่อประเภทการใช้งานอย่างเดียว   (stock_transactions.type)
   ขายสินค้า   ,    เบิกสินค้าเบื่อการตัดคอร์ส   ,    เปลี่ยนสูตรยา(ต้องเก็บ log เพิ่ม)   ,   ตัดคอร์สโดยไม่ใช้สูตรยา
- หมายเลขสัญญาแสดงผิด (contracts.contract_id)
- ผู้อนุมัติ จะเป็นพนักงานที่ทำรายการตัดคอร์ส   (course_cuts.user_id)
- หมายเหตุ (course_cut_medicines.comment)

- ชื่อแพทย์1 ชื่อแพทย์2 และตำแหน่งอื่นๆ คือ พนักงานที่ทำคอร์สนี้ให้ลูกค้าในหน้าตัดคอร์ส(https://www.kkcpos.com/pos-system/course/cut) 
  แต่การให้ค่ามือจะมีทั้งหมด 5 ประเภท ของแต่ละตำแหน่ง (หมอ พยาบาล เทอราปิส กายภาพ)
1.หมอ , พยาบาล , เทอราปิส , กายภาพ
2.ผู้ช่วย
3.เปิดเส้น
4.ฉีดสะโพก
5.สะกิด
  บางคอร์สะมีค่ามือที่ต้องให้พนักงานใน 2 ประเภทใน 1 ตำแหน่ง เช่น หมอ และ ฉีดสะโพก
ในรายงาน  หมอจะอยู่ในช่อง ชื่อแพทย์1  , หมอฉีดสะโพกจะอยู่ในช่อง ชื่อแพทย์2 แต่จะไม่มีเกิน 2 ประเภทใน 1 ตำแหน่ง

**Comment by troyzayne** [comment]
ซัน

**Comment by troyzayne** [comment]
ในช่องรายการถ้าว่าง ให้ประเภทการใช้งาน แสเงข้อมูลเป็น ตัดคอร์สโดยไม่ใช้สูตรยา (ไม่มี table ใน database ให้ show แบบนี้เลย )

**Comment by troyzayne** [comment]
คอลั่มคอร์ส แสดงรายชื่อคอร์สที่ลูกค้าตัดใช้งาน ไม่ว่าจะมีการตัดใช้ยาหรือไม่ ก็ต้องขึ้น **ชื่อคอร์ส**  (contracts.treatment_name)
คอลั่มรายการ ตัวยาที่ใช้ในการตัดคอร์ส **สูตรยา** ถ้ามีการเปลี่ยนยา ก็จะขี้นสูตรยาที่เปลี่ยนใหม่ทั้งหมด (course_cut_medicine.medicine_id) > join table : treatments.id
จำนวนยา = ปริมาณยาที่ใช้ตามสูตร เป็นสูตรยาที่ fix มาอยู่แล้ว จะเปลี่ยนปริมาณก็ต่อเมื่อมีการเปลี่ยนสูตรยา
จำนวนยาก็จะเปลี่ยนตามจำนวนที่ตัดใช้   (สูตรยาของคอร์สอยู่ใน treatment_medicines)
เช่นตัดใช้ 2 สูตรยา A มี 5 ขวด จำนวนยา = 10 ขวด (course_cut_medicines.qty)

จำนวนที่ตัดใช้ = จำนวนคอร์สที่ลูกค้าตัดใช้ (จำนวนรอบนี้ตัด 2 ครั้ง)   (น่าจะ course_cuts.qty)
จำนวนครั้งที่ใช้ได้ = จำนวนคอร์สที่ลูกค้าซื้อ จำนวนนี้จะไม่ลดลง    (contracts.amount)
จำนวนครั้งที่ทำ **เปลี่ยนชื่อเป็นจำนวนครั้งที่เหลือ**  = จำนวนคอร์สที่เหลือ      (contracts.remaining)
ประเภทการใช้งาน = ไม่ต้องมีวงเล็บ (0.0000 บาท) ให้แสดงเป็นชื่อประเภทการใช้งานอย่างเดียว (stock_transactions.type)
ขายสินค้า , เบิกสินค้าเบื่อการตัดคอร์ส , เปลี่ยนสูตรยา(ต้องเก็บ log เพิ่ม) , ตัดคอร์สโดยไม่ใช้สูตรยา

วันที่เอกสาร = วันที่ตัดคอร์ส   (course_cuts.updated_at)

หมายเลขสัญญา = ถูกแล้ว

หมายเหตุ = เหตุผลในการเปลี่ยนสูตรยา     (course_cut_medicines.comment)

ผู้อนุมัติ = คือคน log-in  (course_cuts.user_id)
ชื่อแพทย์ดึงมาจากค่ามือ

@satawat-t ขอ table ด้วยครับ
