### ISSUE TITLE
รายงานสินค้าเข้า-ออกในสต็อค 

### ISSUE THREAD

**Issue by satawat-t** [satawat-t/kkc#18]
https://www.kkcpos.com/report/stock-transaction

table : stock_transactions , stock_transaction_lines

- รหัสรายการ จะแสดงเป็นรหัสสินค้า หรือตัวยา  treatments.treatment_no

แท็ป รายงานสินค้าเข้า  แสดงรายการสินค้าหรือยาที่เพิ่มขึ้นในระบบ
        รายงานสินค้าออก  แสดงรายการสินค้าหรือยาที่ลดลงจากระบบ

รายละเอียดภายในเมื่อกดเข้าไปที่ตัวสินค้า
- ต้องแสดง รหัสลูกค้า ชื่อลูกค้า ถ้ามีการตัดคอร์สและขายสินค้า
ประเภทที่มี   รับเข้า , โอนออก , เบิกสินค้าเพื่อตัดคอร์ส , ขายสินค้า

* เฉพาะสาขาสำนักงานใหญ่ ดูได้ทุกสาขา  สาขาอื่นๆ ดูได้เฉพาะสาขาตัวเอง

**Comment by satawat-t** [comment]
- ลองรับเข้าสินค้า สาขา สำนักงานใหญ่  Aur จำนวน 10 หน่วย
![image](https://user-images.githubusercontent.com/60998712/88754599-4cf3eb00-d189-11ea-81e0-a832cfa06c70.png)
- และโอนสินค้าออกจากสำนักงานใหญ่ Tx-Sponge 2 หน่วย
![image](https://user-images.githubusercontent.com/60998712/88754726-a1976600-d189-11ea-8c60-4c624e128bd4.png)

- มาดูที่รายงาน ฟิลเตอร์สำนักงานใหญ่ และวันที่ 29
  ในรายงานไม่แสดงข้อมูลทั้งแท็ปสินค้าเข้า-ออก
![image](https://user-images.githubusercontent.com/60998712/88754817-e6230180-d189-11ea-8ff5-1dc7fb71af4d.png)

- เมื่อกดแสดงรายละเอียดของสินค้า Url ด้านบนแสดงวันที่ตามที่ค้นหา แต่ในรายการมีวันที่อื่นๆแทรกเข้ามา
![image](https://user-images.githubusercontent.com/60998712/88757009-3f416400-d18f-11ea-964e-528744a28556.png)

- รายการสินค้าต้องแสดงเพียงรายการเดียวในแต่ละแท็ปครับ
  เช่น รายการ 20% s มีการรับเข้าในระบบทั้งหมด 10 transaction  ต้องแสดง 1 รายการ และเป็นผลรวมของจำนวนทุก transaction
  ในแท็ปสินค้าออกก็จะแสดงรายการเดียวเหมือนกันครับ 20% s มีการใช้งานตัดคอร์ส 20 หน่วย , ขาย 50 หน่วย 
  จะต้องแสดงรายการ 20% s 70 หน่วย แค่ 1 row ครับ
 
![image](https://user-images.githubusercontent.com/60998712/88757545-85e38e00-d190-11ea-8175-cdacfc7b7e90.png)

**Comment by satawat-t** [comment]
- เพิ่มช่องค้นหา โดยพิมพ์รหัสหรือชื่อตัวยาได้

**Comment by troyzayne** [comment]
นัท
