### ISSUE TITLE
รายงานสรุปยอดที่ปรึกษาการขาย

### ISSUE THREAD

**Issue by satawat-t** [satawat-t/kkc#19]
https://www.kkcpos.com/report/advisor

table : commission_sales

ขายคอร์ส Filler CC ราคา 22000 บาท
- แบ่งยอดขาย(https://www.kkcpos.com/transaction/sales) ให้ คุณ A จำนวน 11000 บาท และ คุณ B 11000 บาท
ในรายงานนี้ต้องแสดงเป็น
คอลั่ม | สาขา | รหัสพนักงาน | ชื่อ-สกุล | เงินที่ชำระ | ยอดหัก | ยอดสุทธิ |
สำนักงานใหญ่ | A00 | A | 11000 | 1000 | 10000
สำนักงานใหญ่ | B00 | B | 11000 | 1000 | 10000
ในรายงานแสดงรายละเอียด A
คอลั่ม | สาขา | วันที่ | เลขที่ใบเสร็จ | ทรีตเม้นท์ | รหัสพนักงาน | ชื่อ-สกุล | เงินที่ชำระ | ยอดหัก | ยอดสุทธิ | ยอดเซลล์ | กลุ่ม/ประเภท
สำนักงานใหญ่ | 2020-07-22 | RE111111111 | Filler CC | A00 | A | 11000 | 1000 | 10000 | 10000 | Other

- เฉพาะสาขาสำนักงานใหญ่ที่สามารถฟิลเตอร์สาขาได้ สาขาอื่นๆดูได้แค่สาขาตัวเอง

**Comment by troyzayne** [comment]
[รายงานสรุปยอดที่ปรึกษาการขาย 1-8-63.docx](https://github.com/satawat-t/kkc/files/5010003/1-8-63.docx)
<img width="817" alt="Screen Shot 2563-08-01 at 15 03 34" src="https://user-images.githubusercontent.com/67706758/89097327-40c99100-d408-11ea-9f6d-7bc6e79bdd31.png">
<img width="852" alt="Screen Shot 2563-08-01 at 15 03 46" src="https://user-images.githubusercontent.com/67706758/89097330-44f5ae80-d408-11ea-9b55-ce62707df0ed.png">
<img width="807" alt="Screen Shot 2563-08-01 at 15 03 56" src="https://user-images.githubusercontent.com/67706758/89097332-458e4500-d408-11ea-91cb-918c3fa0e2a7.png">

**Comment by troyzayne** [comment]
นัท
