### ISSUE TITLE
รายงานวงเงินคงเหลือ

### ISSUE THREAD

**Issue by satawat-t** [satawat-t/kkc#21]
https://www.kkcpos.com/report/getCustomerBalance/view

table : credit_sale_histories

- ประเภทวงเงิน  table : credit_sale_histories
  giftset_credit_amount  คือ วงเงินถาดแถม
  primary_credit_amount คือ วงเงินหลัก
  secondary_credit_amount คือ วงเงินแถมโปรโมชั่น
  advance_credit_amount  คือ วงเงินมัดจำล่วงหน้า
  cutdown_credit_amount  คือ วงเงินคัตดาวน์

- วงเงินที่ซื้อ คือ วงเงินที่ลูกค้าได้รับเข้าระบบ เช่น การซื้อวงเงินมัดจำล่วงหน้า ซื้อวงเงินหลัก วงเงินคัตดาวน์ที่ได้จากการคัตดาวน์คอร์ส
- วงเงินที่ชำระ คือ ลูกค้าใช้วงเงินแล้ววงเงินลบออกจากระบบ เช่นการเอาวงเงินมัดจำมาซื้อคอร์ส ใช้วงเงินถาดแถมซื้อคอร์ส
- วงเงินคงเหลือ คือ วงเงินที่ลูกค้ามีตาม transaction นั้นๆ

- Filter สาขาได้ สำนักงานใหญ่ดูได้ทุกสาขา สาขาอื่นๆดูได้เฉพาะสาขาตัวเอง

**Comment by satawat-t** [comment]
- ตัวอย่างลูกค้าคนนี้นะครับ มี transaction ติดลบ
![image](https://user-images.githubusercontent.com/60998712/88670547-65bfba80-d10f-11ea-8a09-423b189231a3.png)

- ข้อมูลที่เป็นผลลบ ต้องแสดงในคอลั่ม **วงเงินที่ชำระ** นะครับ เพราะลูกค้าได้เสียวงเงินออกจากระบบไป
  คอลั่ม**วงเงินที่ซื้อ** จะเป็นข้อมูลที่ไม่ติดลบเท่านั้นครับ
![image](https://user-images.githubusercontent.com/60998712/88670607-796b2100-d10f-11ea-8fa1-cbf64e8a23e4.png)

- และประเภทวงเงิน ตามรายละเอียดด้านบนของ issue ไม่มีข้อมูลของประเภทวงเงินที่เป็น **อื่นๆ** ครับ
  น่าจะดึงข้อมูล credit_type = advance_credit_amount มาแสดงครับ แต่มันต้องแสดงเป็นชื่อประเภท **"วงเงินมัดจำล่วงหน้า"** ครับ
![image](https://user-images.githubusercontent.com/60998712/88671227-3fe6e580-d110-11ea-9e27-fc2a53db2af6.png)

- แล้วก็ลองค้นหาแล้วขึ้น Exception แบบนี้ครับ (ไม่มีฟิลด์ remaining2 ในระบบครับ)
![image](https://user-images.githubusercontent.com/60998712/88671780-ea5f0880-d110-11ea-9d0f-3eb3062bfd1b.png)

**Comment by satawat-t** [comment]
เพิ่ม Filter สาขาครับ

**Comment by troyzayne** [comment]
Auditor Passed

**Comment by troyzayne** [comment]
ตย. ซื้อสินค้าที่เข้าเงื่อนไข วงเงินถาดแถม 50 % #11  

A. ซื้อคอร์สที่ได้วงเงินแถม 50%

ซื้อคอร์สปกติ ราคา 10,000 บาท ได้วงเงินแถม **5,000** บาท 
แบ่งจ่ายเป็น 2 งวด วงเงินถาดแถมคิดจากยอดเงินที่ชำระจริง

งวดแรก 
2/8/20 ชำระ 7,000 บาท จะได้วงเงินแถม **3,500** บาท ยอด 3,500 บาท ใส่ในช่องวงเงินที่ซื้อ
10/8/20 ชำระ 3,000 บาท จะได้วงเงินแถม **1,500** บาท ยอด 1,500 บาท ใส่ในช่องวงเงินที่ซื้อ

ช่องวงเงินที่ชำระ เปลี่ยนเป็นคำว่า **วงเงินที่ใช้ไป** = ลค ใช้วงเงินจากคอร์สในถาดแถมไปเท่าไหร่ เอาจำนวนที่ใช้ไปมาใส่

ช่องวงเงินคงเหลือ คือ 
วงเงินถาดแถมที่ลูกค้ามีอยู่ก่อนหน้านี้ เช่น ลค มี วงเงินถาดแถม 100,000 บาท

วันที่ 2/8/20 ได้วงเงินแถม 3,500 บาท ช่องวงเงินคงเหลือจะกลายเป็น 100,000 + 3,500 บาท = 103,500 บาท
ถ้าวันที่ 2/8/20 ใช้วงเงินถาดแถมไป 13,500 บาท ช่องวงเงินคงเหลือ จะเป็น 103,500 - 13,500 = 90,000 บาท 

                                                                                 วงเงินที่ซื้อ     วงเงินที่ใช้      วงเงินคงเหลือ
2/8/20 19.00 น. ประเภทวงเงินถาดแถม                       3,500                                 103,500
2/8/20 20.00 น. ประเภทวงเงินถาดแถม                                             13,500          90,000

วันที่ 10/8/20 
ชำระ 3,000 บาท จะได้วงเงินแถม **1,500** บาท ยอด 1,500 บาท ใส่ในช่องวงเงินที่ซื้อ
ถ้ามีการชำระเข้ามาใช้ถาดแถมในวันนี้ 10,000 บาท

10/8/20 19.00 น. ประเภทวงเงินถาดแถม                      1,500                                 91,500   (90,000  + 1,500)
10/8/20 20.00 น. ประเภทวงเงินถาดแถม                                          10,000           81,500   (90,000 + 1,500 -10,000) 

B. ซื้อคอร์สที่**ไม่ได้วงเงินแถม 50%** จะไม่ show course นั้นมาในรายงาน 
    
@satawat-t

**Comment by troyzayne** [comment]
<img width="869" alt="Screen Shot 2563-08-06 at 12 42 44" src="https://user-images.githubusercontent.com/67706758/89495400-6082ff80-d7e2-11ea-9d25-bcc288272840.png">
<img width="875" alt="Screen Shot 2563-08-06 at 12 42 52" src="https://user-images.githubusercontent.com/67706758/89495405-6547b380-d7e2-11ea-979d-a64a671863a8.png">
