### ISSUE TITLE
จะคัตดาวน์ คอสร์สเป็นวงเงินค่ะ แต่ระบบแจ้งว่า เกิดข้อผิดพลาดค่ะ

### ISSUE THREAD

**Issue by troyzayne** [satawat-t/kkc#27]
ระบบไม่สามารถ cutdown + up course ได้ใน buffet

**Comment by troyzayne** [comment]
<img width="1180" alt="Screen Shot 2563-08-01 at 20 30 27" src="https://user-images.githubusercontent.com/67706758/89102712-00810780-d436-11ea-85a5-3fe42dd22297.png">
<img width="1211" alt="Screen Shot 2563-08-01 at 20 31 14" src="https://user-images.githubusercontent.com/67706758/89102715-0676e880-d436-11ea-9b5a-6e1230b31e95.png">

**Comment by satawat-t** [comment]
http://128.199.187.187/customer/information/index
Video : https://drive.google.com/file/d/1jcS4TrxNItbiErgTl4lETF6ByBsKlAZs/view?usp=sharing
table เก็บสัญญาและคอร์สจะอยู่ใน contracts
** บางคอร์สจะมีป๊อปอัพเด้งข้อผิดพลาด อยากให้ข้าม pop-up นี้ไปครับ
