### ISSUE TITLE
การเพิ่มวงเงินถาดแถม จะเพิ่มจากการชำระเงิน (ขอ table และ VDO ให้ด้วยครับ)

### ISSUE THREAD

**Issue by troyzayne** [satawat-t/kkc#29]
เช่น
1/08/20 
ซื้อคอร์ส 10,000 บาท ชำระเงิน 6000 บาท จะได้ถาดแถม 50% คือ 3000 บาท
10/08/20
ชำระเพิ่ม 4000 บาท จะได้ถาดแถม 50% คือ 2000 บาท 

ปัจจุบัน ผิด คิดคำนวนถาดแถม 50% จากจำนวนที่ซื้อ และจะมาแสดงผลในรายงาน 3. รายงานวงเงินคงเหลือ 
[ข้อ 3 รายงานวงเงินคงเหลือ แจ้งแก้ไข 3-8-63 @Assada(1).docx](https://github.com/satawat-t/kkc/files/5020440/3.3-8-63.%40Assada.1.docx)

@satawat-t ขอ table และ VDO ให้ด้วยครับ

**Comment by satawat-t** [comment]
- ให้ไปคำณวนที่ยอดชำระครับ ตอนนี้ระบบน่าจะคำณวนผิดที่มูลค่าสัญญา
![image](https://user-images.githubusercontent.com/60998712/89262013-36520600-d659-11ea-9501-0ba744fd98f2.png)
- ในหน้าชำระเพิ่มจะคิดวงเงินถาดแถมให้ลูกค้า ตามเงื่อนไขเดียวกับหน้าขายคอร์ส คือไม่คิดวงเงินถาดแถมให้ลูกค้ากรณีซื้อสินค้าหรือคอร์สบางตัว
https://drive.google.com/file/d/1gooIyxV9a8YG9GYsa6yqUuS7fevwOend/view?usp=sharing

**Comment by IbanezHcu** [comment]
[ข้อ 9. การเพิ่มวงเงินถาดแถม จะเพิ่มจากการชำระเงิน (ขอ table และ VDO ให้ด้วยครับ) #29.docx](https://github.com/satawat-t/kkc/files/5050086/9.table.VDO.29.docx)

**Comment by IbanezHcu** [comment]
การเพิ่มวงเงินถาดแถม จะเพิ่มจากการชำระเงิน (ขอ table และ VDO ให้ด้วยครับ) #29


![image](https://user-images.githubusercontent.com/69230636/89770987-c72d5380-db29-11ea-9107-8d3d84bd8d26.png)












ซื้อคอร์ส 10,000 บาท ชำระเงิน 6000 บาท จะได้ถาดแถม 50% คือ 3000 บาท (ถูกต้องแล้ว)

ชำระเพิ่ม 4000 บาท จะได้ถาดแถม 50% คือ 2000 บาท (ถูกต้องแล้ว)



ไม่สามารถตรวจสอบได้ เนื่องจาก  รายงานวงเงินคงเหลือ ไม่สามารถเข้าได้ครับ 

![image](https://user-images.githubusercontent.com/69230636/89771058-ec21c680-db29-11ea-8264-6e4dfb6b374e.png)

![image](https://user-images.githubusercontent.com/69230636/89771077-f2b03e00-db29-11ea-8383-f087c16537ef.png)

**Comment by troyzayne** [comment]
@IbanezHcu รายงานวงเงินคงเหลือเข้าได้ครับ 

http://128.199.187.187/report/getCustomerBalance/view

<img width="1275" alt="Screen Shot 2563-08-16 at 11 21 14" src="https://user-images.githubusercontent.com/67706758/90326454-b4e06900-dfb2-11ea-9ef7-bb59ceab852e.png">
