### ISSUE TITLE
หน้าขายคอร์ส เมื่อคอร์สมากกว่า 1 ตัว ระบบจะบันทึก type_contract = product

### ISSUE THREAD

**Issue by satawat-t** [satawat-t/kkc#3]
https://www.kkcpos.com/pos-system/course/sale

table : contracts
table คอร์สและสินค้า : treatments

- User ทำการคีย์**คอร์ส**หลายตัวใน 1 เลขที่สัญญา เมื่อระบบบันทึกลง table : contracts จะบันทึก type_contract = normal แค่คอร์สแรกครับ
คอร์สถัดไปจะแสดงเป็น product ทำให้หน้าตัดคอร์ส (https://www.kkcpos.com/pos-system/course/cut) ไม่ขึ้นคอร์สให้ตัดครับ
![image](https://user-images.githubusercontent.com/60998712/88446653-0be09b80-ce56-11ea-9d45-b838a5f529b5.png)

**Comment by troyzayne** [comment]
kit
