### ISSUE TITLE
Server Test และ Server จริง 

### ISSUE THREAD

**Issue by troyzayne** [satawat-t/kkc#30]
Server Test จะใช้ตรวจสอบ program bug เท่านั้นก่อนขึ้นจริง 
 http://128.199.187.187/
 kkc_admin pass: kkcpos000

Server จริง kkcpos.com จะใช้ตรวจสอบรายงานเท่านั้น
www.kkcpos.com 

@satawat-t

**Comment by satawat-t** [comment]
@troyzayne ผมรบกวนขอ ip address/user,pass เพื่อเข้าฐานข้อมูลของ Server Test หน่อยครับ
