### ISSUE TITLE
ยกเลิกใบเสร็จ วงเงินมัดจำหรือวงเงินล่วงหน้า ไม่ถูกลบออก ยังคงค้าง 50,000.-  

### ISSUE THREAD

**Issue by troyzayne** [satawat-t/kkc#32]
1 คีย์มัดจำวงเงิน  (วงเงินล่วงหน้า)  50,000.-  ลูกค้าได้วงเงินถาดแถม  25,000.-  (ถูกต้องค่ะ)  
 และทำการยกเลิกใบเสร็จ  วงเงินถาดแถมก็ถูกยกเลิกด้วย    (ถูกต้องค่ะ)   แต่ วงเงินมัดจำหรือวงเงินล่วงหน้า ไม่ถูกลบออก ยังคงค้าง 50,000.- 
<img width="565" alt="Screen Shot 2563-08-05 at 18 07 25" src="https://user-images.githubusercontent.com/67706758/89405922-8b1f7a80-d746-11ea-8cce-cf76e844a1dd.png">

#11

**Comment by IbanezHcu** [comment]
หน้ายกเลิกใบเสร็จ หากเป็นรายการวงเงินมัดจำล่วงหน้าหรือวงเงินแถมวงเงิน จะไม่สามารถยกเลิกได้ มี error ดังรูป


![image](https://user-images.githubusercontent.com/69230636/90597991-66360780-e21c-11ea-91a8-d1aec9af42ad.png)

ใน  contracts.treatment_id วงเงินแถมคอร์ส สามารถยกเลิกได้  เนื่องจากระบบเจอคอร์สใน treatment_id   แต่วงเงินมัดจำล่วงหน้าและวงเงินแถมวงเงิน ระบบไม่เจอข้อมูล treatment_id ครับ 

![image](https://user-images.githubusercontent.com/69230636/90598639-a1850600-e21d-11ea-81a8-d20638ad430a.png)

**Comment by IbanezHcu** [comment]
ซื้อวงเงิน 150000 แถม Botox 50U  ยกเลิกใบเสร็จแล้ววงเงินหลักไม่ถูกคืน

![image](https://user-images.githubusercontent.com/69230636/90723110-5aaf1300-e2e6-11ea-84a1-192ac6dce453.png)
