### ISSUE TITLE
หน้าขายคอร์ส การขายวงเงิน สามารถขายได้หลายจำนวน

### ISSUE THREAD

**Issue by satawat-t** [satawat-t/kkc#4]
https://www.kkcpos.com/pos-system/course/sale

table วงเงิน : credit_sale_types

- ในหน้าขายคอร์ส ประเภท**ขายวงเงิน** ทำให้สามารถขายวงเงินได้หลายตัว
   เช่น ขายวงเงิน 100 บาท กับ ขายวงเงิน 1073 บาท  (ปัจจุบันจะขายได้ 1 วงเงิน/1 สัญญา)
![image](https://user-images.githubusercontent.com/60998712/88446749-e43e0300-ce56-11ea-922e-bb6af4faa762.png)

- และถ้าซื้อวงเงิน 1 วงเงิน  ตัวอย่างซื้อวงเงิน 10 บาท ทำให้สามารถใส่จำนวนได้ ถ้าต้องการจะซื้อวงเงิน 100 บาท
  เช่น ให้ใส่เป็นจำนวน 10 แล้วระบบจะคูณให้เองเลย
![image](https://user-images.githubusercontent.com/60998712/88446772-12234780-ce57-11ea-8983-846ae8981de9.png)

**Comment by satawat-t** [comment]
กระทบไปที่หน้ายกเลิกใบเสร็จรับเงิน (Phase2)

**Comment by troyzayne** [comment]
kit
