### ISSUE TITLE
ฟังก์ชั่นหลังบ้าน

### ISSUE THREAD

**Issue by IbanezHcu** [satawat-t/kkc#42]
**1.หน้าแก้ไข Product/Treatment**  เวลาเพิ่มหรือแก้ไขคอร์ส  ในช่อง หน่วย จะแสดงเป็น “ขวด” 

เวลาเลือกหน่วย เช่น เลือกเป็น ml. ใน database เก็บค่าเป็น ml.จริง  แต่ในหน้า แก้ไข Product/Treatment   แสดงหน่วยเป็น “ขวด” 

![image](https://user-images.githubusercontent.com/69230636/90092143-54eb8780-dd52-11ea-87a1-484a210a97d1.png)

![image](https://user-images.githubusercontent.com/69230636/90092153-5b79ff00-dd52-11ea-9d37-7852b4a14c93.png)

**Comment by satawat-t** [comment]
**2.หน้าแก้ไขสัญญา**
http://128.199.187.187/modify-contract/
- คอร์สที่เป็น Buffet ให้ group รวมชื่อคอร์สให้แสดงรายการเดียว เช่น KKC Pack 1 (Bronz) ไม่ต้องแสดงคอร์สย่อย
![image](https://user-images.githubusercontent.com/60998712/91927481-d3a96400-ed03-11ea-98a7-c517089491b1.png)

- ไม่แน่ใจว่า session กับ per session ไว้แก้อะไรนะครับ  แต่ในระบบเดิม เค้าจะแก้จำนวนครั้งที่ใช้งานคอร์สได้ (session)
   contracts.remaining,ราคาต่อหน่วย (per session) contracts.price  และ total amount จะเปลี่ยนค่าตามสูตร session * per session = total amount
![image](https://user-images.githubusercontent.com/60998712/91927429-ad83c400-ed03-11ea-90c7-733d5e63a26f.png)
