### ISSUE TITLE
Issues Edit ประวัติการตัดใช้ 

### ISSUE THREAD

**Issue by troyzayne** [satawat-t/kkc#45]
Issues Edit ประวัติการตัดใช้ 
<img width="1018" alt="Screen Shot 2563-08-14 at 17 51 51" src="https://user-images.githubusercontent.com/67706758/90242257-dcbaba00-de56-11ea-854d-76847e451a04.png">

**Comment by IbanezHcu** [comment]
Edit ประวัติการตัดใช้ #45

หน้าจัดการสูตรยาแสดงรายการถูกต้อง แต่หน้าประวัติการตัดใช้ แสดงรายละเอียดสูตรไม่ถูกต้อง

![image](https://user-images.githubusercontent.com/69230636/90496976-b5bef980-e170-11ea-82f1-e5448ca3d153.png)

![image](https://user-images.githubusercontent.com/69230636/90497021-c8d1c980-e170-11ea-9bfc-04962eb392f9.png)

![image](https://user-images.githubusercontent.com/69230636/90497036-ce2f1400-e170-11ea-8478-d664dbfa0216.png)

![image](https://user-images.githubusercontent.com/69230636/90497046-d1c29b00-e170-11ea-9af3-49dc42a61c9b.png)
