### ISSUE TITLE
Sale transaction แสดงราคารวมของคอร์สผิด

### ISSUE THREAD

**Issue by satawat-t** [satawat-t/kkc#46]
![image](https://user-images.githubusercontent.com/60998712/90354576-ebca8380-e073-11ea-9642-2fd170e8abe1.png)
- ทำการขายคอร์ส AHA Peel 001 ราคา 1,500 บาท  และ Anti Wrinkle TM 001 ราคา 7,500 บาท
- แต่ในหน้าแบ่งยอดขาย แสดงราคารวมเป็น 9000 ทั้งคู่ครับ(ผิด) ต้องแสดงเป็น 1500 ก้บ 7500
![image](https://user-images.githubusercontent.com/60998712/90354680-30eeb580-e074-11ea-8c7a-df611bfe5436.png)

**Comment by IbanezHcu** [comment]
เคสเพิ่มเติม 19/08/20  ขายคอร์สบุฟเฟ่ต์แล้ว หน้าแบ่งยอดไม่แสดงรายการ
![image](https://user-images.githubusercontent.com/69230636/90626076-a7421200-e244-11ea-95fe-fe6d9180ca68.png)

**Comment by IbanezHcu** [comment]
[หน้าแบ่งยอดขาย ซื้อคอร์สบุฟเฟ่ต์ ระบบไม่แสดงรายการในหน้าแบ่งยอด.docx](https://github.com/satawat-t/kkc/files/5095895/default.docx)

**Comment by troyzayne** [comment]
<img width="1276" alt="Screen Shot 2563-08-19 at 15 49 46" src="https://user-images.githubusercontent.com/67706758/90631127-62ba7480-e24c-11ea-9fa0-65df34359c20.png">
