### ISSUE TITLE
Performance หน้าขายคอร์สและตัดคอร์สโหลดช้า

### ISSUE THREAD

**Issue by IbanezHcu** [satawat-t/kkc#51]
เข้าหน้าตัดคอร์ส > ค้นหาลูกค้า พอกดชื่อลูกค้าที่ต้องการแล้ว ต้องรอประมาณ 30 วินาที หรือ มากกว่านั้น

![image](https://user-images.githubusercontent.com/69230636/90652312-239a1c80-e268-11ea-912e-f0631a7090fc.png)
![image](https://user-images.githubusercontent.com/69230636/90652334-298ffd80-e268-11ea-9ab6-d82c202e7390.png)
 ลิ้งค์หน้าตัดคอร์ส
http://128.199.187.187/pos-system/course/cut/Pnmk72fTZQIdXnZ2

**Comment by IbanezHcu** [comment]
เพิ่มเติม หน้าขายคอร์สก็โหลดช้าครับ

**Comment by troyzayne** [comment]
หน้าตัดคอร์สขึ้นดับเบิ้ล 

![78310](https://user-images.githubusercontent.com/67706758/90948114-6e34b800-e465-11ea-8c3e-f27d55d4c916.jpg)


<img width="1218" alt="Screen Shot 2563-08-22 at 10 49 34" src="https://user-images.githubusercontent.com/67706758/90948083-36c60b80-e465-11ea-8f79-918a955bda2e.png">
