### ISSUE TITLE
ยกเลิกใบเสร็จวงเงินมัดจำล่วงหน้าไม่ได้ 

### ISSUE THREAD

**Issue by IbanezHcu** [satawat-t/kkc#52]
กดยกเลิกใบเสร็จ รายการวงเงินมัดจำล่วงหน้า แล้ว Error 

![image](https://user-images.githubusercontent.com/69230636/90597991-66360780-e21c-11ea-91a8-d1aec9af42ad.png)

**Comment by IbanezHcu** [comment]
ใน contracts.treatment_id  วงเงินมัดจำล่วงหน้าและวงเงินแถมวงเงิน ใน  treatment_id เก็บค่าเป็น null ครับ
![image](https://user-images.githubusercontent.com/69230636/90722816-bdec7580-e2e5-11ea-947c-cc9493a5e936.png)

**Comment by troyzayne** [comment]
#32
