### ISSUE TITLE
ยกเลิกใบเสร็จรับเงิน เก็บ Log,คืนค่าวงเงิน

### ISSUE THREAD

**Issue by satawat-t** [satawat-t/kkc#53]
http://128.199.187.187/pos-system/course/payment/cancel
1. เมื่อมีการยกเลิกใบเสร็จที่เป็นการขายสินค้า จะต้องมีการคืนสต็อคสินค้าด้วย (น่าจะมีฟังก์ชั่นนี้แล้ว) แต่จะต้องเก็บ Log เพิ่มเติมสำหรับรายงานสินค้าเข้า-ออกในสต็อค  เพิ่มคอลั่ม deleted_at ใน table : stock_transactions  เมื่อมีการยกเลิกใบเสร็จจากการขายสินค้า stock_transactions.deleted_at จะถูกใส่ค่าวันที่ เป็นวันที่ยกเลิกใบเสร็จ
* จะรู้ได้จาก sale_payments.contract_id join contracts.contract_id ดูคอลั่ม type_contract = product  คือการขายสินค้า

**Comment by IbanezHcu** [comment]
ยกเลิกใบเสร็จแล้ว วงเงินไม่ถูกคืน

* กรณีที่1
ซื้อคอร์ส วงเงินหลัก 100000 บาท ลูกค้าได้วงเงินหลัก 100000 บาท  (customers.primary_credit_amount = 100000) ถูกต้องแล้ว
ทำการยกเลิกใบเสร็จ รายการวงเงิน 100000 บาท  ระบบต้องดึงวงเงินหลักที่ลูกค้าได้ไป คืน  (customers.primary_credit_amount )


* กรณีที่2
ซื้อคอร์ส วงเงินหลัก 300000 บาท แถมวงเงิน 50000 บาท   ลูกค้าได้วงเงินหลัก 300000 บาท (customers.primary_credit_amount = 300000) และได้ วงเงินแถมโปรโมชั่น 50000 บาท (customers.secondary_credit_amount = 50000)

ทำการยกเลิกใบเสร็จ รายการวงเงินหลัก 300000 บาท แถมวงเงิน 50000 บาท   ระบบต้องดึงวงเงินหลักที่ลูกค้าได้ไป คืน  (customers.primary_credit_amount )และต้องดึงวงเงินแถมโปรโมชั่นที่ลูกค้าได้ไปคืน (customers.secondary_credit_amount )
