### ISSUE TITLE
ซื้อคอร์สด้วยวงเงินทุกชนิด ต้องไม่ได้ถาดแถม 

### ISSUE THREAD

**Issue by IbanezHcu** [satawat-t/kkc#55]
1.
![image](https://user-images.githubusercontent.com/69230636/90853557-b2ac4f00-e3a4-11ea-90ca-7db819f7d804.png)

ตัวอย่าง จะทำการซื้อคอร์ส และชำระเงินโดยใช้วงเงินหลัก    วงเงินหลักตอนนี้มียอดอยู่ 300000 บาท 
(Primary_credit_amount = 300000)  เมื่อทำการซื้อคอร์สด้วยวงเงินหลักราคา  12000 บาท 
วงเงินหลักจะต้องเหลือ 288000 บาท  (Primary_credit_amount = 288000) ถูกแล้ว   และต้องไม่ได้วงเงินถาดแถม  (Gift_Set_credit_amount = 0)

![image](https://user-images.githubusercontent.com/69230636/90853626-e38c8400-e3a4-11ea-9c51-317fab8ff1b6.png)

![image](https://user-images.githubusercontent.com/69230636/90853711-1f274e00-e3a5-11ea-9f2c-3548dab85461.png)

ทำการซื้อคอร์ส     ถอดขนตา , Acne Clear 001 , Acne Clear Mask 001   อย่างละ 1 คอร์ส   ยอดรวม 12000 บาท

![image](https://user-images.githubusercontent.com/69230636/90854203-898cbe00-e3a6-11ea-9edb-d4184f418151.png)

ทำการชำระด้วย วงเงินหลัก 12000   บาท   

![image](https://user-images.githubusercontent.com/69230636/90854222-97424380-e3a6-11ea-93e0-1d555ccfc8c4.png)

![image](https://user-images.githubusercontent.com/69230636/90854237-a1644200-e3a6-11ea-917d-ae659ab13382.png)

ลูกค้าได้ถาดแถม 6000  ซึ่งจริงๆต้องไม่ได้ถาดแถม (Gift_Set_credit_amount = 0)

**Comment by IbanezHcu** [comment]
*
2. มีวงเงินหลักอยู่ 250000 บาท  (primary_credit_amount = 250000) 
มีวงเงินแถมโปรโมชั่น  อยู่100000 บาท  (secondary_credit_amount = 100000) 

![image](https://user-images.githubusercontent.com/69230636/90865226-3faed280-e3bc-11ea-8e62-1101d3a5fe06.png)

ทำการซื้อวงเงินหลัก 300000 แถมวงเงิน 50000 บาท

![image](https://user-images.githubusercontent.com/69230636/90864841-9e278100-e3bb-11ea-9653-ef8eb162dcd5.png)



วงเงินหลักเพิ่มขึ้น 300000 (primary_credit_amount = 550000) ถูกต้อง  
แต่วงเงินแถมโปรโมชั่น ไม่ถูกเพิ่ม   
ที่ถูกต้องคือ วงเงินแถมโปรโมชั่น ต้องเพิ่มขึ้น 50000 บาท   (secondary_credit_amount  = 150000)

![image](https://user-images.githubusercontent.com/69230636/90865081-0d04da00-e3bc-11ea-8370-9b4f54e74f12.png)

**Comment by satawat-t** [comment]
https://www.kkcpos.com/admin/credit-sales-type/15/edit
- ขายวงเงินตัวนี้มูลค่า 20000 บาท ลูกค้าต้องได้วงเงิน 27000 บาท  แต่ระบบให้วงเงินลูกค้าแค่ 20000 บาท
![image](https://user-images.githubusercontent.com/60998712/91684948-155ed100-eb83-11ea-91f9-3a545563711c.png)

table : credit_sale_type
![image](https://user-images.githubusercontent.com/60998712/91685074-71c1f080-eb83-11ea-8539-e93937b02666.png)
