### ISSUE TITLE
หน้าตัดคอร์ส ตัดคอร์สบางตัวแล้วคอร์สไม่ลดลง

### ISSUE THREAD

**Issue by satawat-t** [satawat-t/kkc#6]
https://www.kkcpos.com/pos-system/course/cut/

table : course_cut  เก็บค่าประวัติการตัดคอร์ส
table : contracts  เก็บค่าจำนวนที่ลูกค้าใช้งานคอร์สได้

   ตัดคอร์สแล้วจำนวนคอร์สที่เหลือไม่ลดลง แต่มีประวัติการตัดคอร์สเกิดขึ้นแล้ว ทำให้ลูกค้ามีคอร์สการใช้งานมากกว่าความเป็นจริง
- คลิปนี้เป็นคลิปที่เจอสาเหตุ ผมลองจากการขายถาดแถมครับ  แต่ User บอกว่าคอร์สอื่นก็เป็น
https://drive.google.com/file/d/15W24DBYEnBktK_HRaAysKKX6VfhFBW9r/view?usp=sharing

**Comment by satawat-t** [comment]
เกิดจาก contracts.start_date,expire_date เป็น null

**Comment by troyzayne** [comment]
kit

**Comment by IbanezHcu** [comment]
ทดสอบใน Server Test แล้ว จำนวนคอร์สลดลงถูกต้องครับ
