### ISSUE TITLE
เก็บรายละเอียดรายงานทุกตัว

### ISSUE THREAD

**Issue by satawat-t** [satawat-t/kkc#60]
รายงานวงเงินถาดแถม  (credit_sale_histories)
![image](https://user-images.githubusercontent.com/60998712/91295837-e1bc2980-e7c5-11ea-8b69-95f6e68a4ddc.png)
- รายการวงเงินยังไม่แสดง

รายงานวงเงินคงเหลือ  (credit_sale_histories)
![image](https://user-images.githubusercontent.com/60998712/91295894-f3053600-e7c5-11ea-809e-a9fb5df93d53.png)
- คอลั่มวงเงินคงเหลือ เป็นค่าว่าง
![image](https://user-images.githubusercontent.com/60998712/91295926-00222500-e7c6-11ea-99ff-09f2869bd63f.png)
- คอลั่มเป็น - เพราะ credit_sale_histories.transaction_amount = 0

**Comment by IbanezHcu** [comment]
รายงานต้องแยกตามสาขาที Login และไม่สามารถฟิลเตอร์เลือกสาขาได้

![image](https://user-images.githubusercontent.com/69230636/91523191-47bfc280-e926-11ea-8db5-daa2df850046.png)

รายงานที่พบปัญหา
- รายงานถาดแถม ต้องแยกตามสาขา ไม่สามารถฟิลเตอร์ได้   http://128.199.187.187/report/advance
- รายงานค่าคอมมือ ต้องแยกตามสาขา ไม่สามารถฟิลเตอร์ได้   http://128.199.187.187/report/onhand-commission
- รายงานยกเลิกการขาย ต้องแยกตามสาขา ไม่สามารถฟิลเตอร์ได้   http://128.199.187.187/report/sale-cancel
- รายงานยกเลิกการตัดคอร์ส ต้องแยกตามสาขา ไม่สามารถฟิลเตอร์ได้   http://128.199.187.187/report/cut-course-cancel

**Comment by satawat-t** [comment]
- รายงานยอดสต็อคคงเหลือรายวัน เข้าสาขา พรอมานาด  แต่ export ออกมาแสดงทุกสาขา
![image](https://user-images.githubusercontent.com/60998712/91687588-4ee70a80-eb8a-11ea-8083-0def2850af1e.png)
