### ISSUE TITLE
Issues รวม Meeting

### ISSUE THREAD

**Issue by IbanezHcu** [satawat-t/kkc#61]

**Comment by IbanezHcu** [comment]
1.รายงานต้องแยกตามสาขาที Login และต้องไม่สามารถฟิลเตอร์เลือกสาขาได้

![image](https://user-images.githubusercontent.com/69230636/91520786-53a88600-e920-11ea-846b-20e09da76a58.png)

รายงานที่พบปัญหา
- รายงานถาดแถม ต้องแยกตามสาขา ต้องไม่สามารถฟิลเตอร์ได้   http://128.199.187.187/report/advance
- รายงานค่าคอมมือ ต้องแยกตามสาขา ต้องไมสามารถฟิลเตอร์ได้   http://128.199.187.187/report/onhand-commission
- รายงานยกเลิกการขาย ต้องแยกตามสาขา ต้องไม่สามารถฟิลเตอร์ได้   http://128.199.187.187/report/sale-cancel
- รายงานยกเลิกการตัดคอร์ส ต้องแยกตามสาขา ต้องไม่สามารถฟิลเตอร์ได้   http://128.199.187.187/report/cut-course-cancel

**Comment by IbanezHcu** [comment]
2.ระบบต้องไม่สามารถตัดสต๊อคเกินจำนวนคงเหลือได้

![image](https://user-images.githubusercontent.com/69230636/91520933-c7e32980-e920-11ea-8cc5-b3ec1a9551fb.png)

**Comment by IbanezHcu** [comment]
3.แก้ไขรายงาน Excel ให้แสดงตัวเลขเป็นรูปแบบ String  ทุกรายงาน

![image](https://user-images.githubusercontent.com/69230636/91521020-f234e700-e920-11ea-8d63-22c8d98eb670.png)

เช่น 
- รายงานยอดขายสาขา
http://128.199.187.187/report/sale-branch
- รายงานแบ่งยอดแต่ละสาขา
http://128.199.187.187/report/branch-commission
- รายงานค่าธรรมเนียม 
http://128.199.187.187/report/payment-fee

**Comment by IbanezHcu** [comment]
4. (แก้ไขแล้ว)  หน้าขายสินค้า > เลือกสินค้า  ให้แสดงมูลค่ารวม เป็นจำนวนเต็ม   

![image](https://user-images.githubusercontent.com/69230636/91521798-b1d66880-e922-11ea-9f8d-35a4e04accca.png)

**Comment by IbanezHcu** [comment]
5. (แก้ไขแล้ว)  Issues คีย์วงเงิน แถม botox & sale transaction กลับมาเป็นซ้ำ

**Comment by IbanezHcu** [comment]
6.หน้าขายถาดแถม ต้องไม่สามารถแก้ไขยอดชำระและราคาต่อหน่วยได้
   
ให้แก้ไขได้เฉพาะจำนวน

![image](https://user-images.githubusercontent.com/69230636/91527859-c6b9f880-e930-11ea-9fbd-de67b956e36c.png)

**Comment by IbanezHcu** [comment]
7. (แก้ไขแล้ว) เพิ่มข้อมูลการชำระเงิน Voucher EP-EQ

![image](https://user-images.githubusercontent.com/69230636/91522619-e6e3ba80-e924-11ea-83c6-49d0810db353.png)

**Comment by IbanezHcu** [comment]
8.กำหนดเงื่อนไขการชำระต่ำกว่า % ที่ตั้งไว้และการตัดคอร์ส 

- คอร์สปกติ หากจำนวนคอร์สมี 1 คอร์ส ต้องชำระ 100% จึงจะสามารถตัดคอร์สได้
- คอร์สปกติ หากจำนวนคอร์สมี 2,3,4 คอร์ส ต้องชำระขั้นต่ำ 50-99% จึงจะสามารถตัดคอร์สได้ 1 ครั้ง และต้องชำระ 100% จึงจะสามารถตัดคอร์สได้ทั้งหมด
- คอร์สปกติ หากจำนวนคอร์สมี 5 คอร์สขึ้นไป ต้องชำระขั้นต่ำ 20-39%  จึงจะสามารถตัดคอร์สได้ 1 ครั้ง  หากชำระตั้งแต่ 40-99% จะสามารถตัดคอร์สได้ 2 ครั้ง  ชำระ 100% สามารถตัดคอร์สได้ทั้งหมด

- คอร์ส Promotion 
- คอร์ส Package
- คอร์ส บุฟเฟ่ต์

![image](https://user-images.githubusercontent.com/69230636/91522943-9fa9f980-e925-11ea-81cd-baa5f8ce81a1.png)

**Comment by IbanezHcu** [comment]
9.(แก้ไขแล้ว)  หน้าประวัติลูกค้า รายการด้านล่างต้องไม่มีปุ่มลบคอร์ส

![image](https://user-images.githubusercontent.com/69230636/91523101-0b8c6200-e926-11ea-90af-c21b793102d3.png)

**Comment by satawat-t** [comment]
10.เงื่อนไขการขายคอร์ส เพื่อดักไม่ให้ user คีย์ผิดพลาด
1 ถ้าคอร์สนั้นมีการค้างชำระมากกว่า 1 คอร์ส ให้ user แยกบิลที่ค้างชำระออกไปอีกบิลนึง
- ตรวจสอบจากการซื้อคอร์ส ถ้ามีมากกว่า 1 แล้วจำนวนเงินที่ชำระ ไม่เท่ากับ มูลค่าสัญญา ให้แสดงข้อความแจ้งเตือน ดักไว้ตรงปุ่มบันทึกในหน้าชำระเงิน
**" ไม่สามารถทำการชำระเงินได้ เนื่องจากมีคอร์สที่ชำระไม่เต็มจำนวน ภายในเลขที่สัญญาเดียวกัน (กรุณาแยกการขายคอร์สที่ค้างชำระเป็นอีก 1 เลขที่สัญญา) "**

2.ถ้าขายมากกว่า 1 ทรีตเม้นท์ ใน 1 ใบเสร็จ การชำระ ห้ามมีเงินสดกับวงเงินรวมกัน
- เช็คจาก payment_machine_id  ถ้ามีการชำระเงินสดหรืออื่นๆ รวมกับ วงเงิน จะขายได้แค่ 1 ทรีตเม้นท์,1คอร์ส หากมีมากกว่า 1 คอร์ส และมีการชำระเงินสดรวมกับวงเงิน ให้แยกไปขายอีก 1 บิล ดักไว้ตรงปุ่มบันทึกในหน้าชำระเงิน
**" ไม่สามารถทำการชำระเงินได้ เนื่องจากการมีประเภทการชำระเป็นวงเงินภายในเลขที่ใบเสร็จเดียวกัน (กรุณาแยกการชำระวงเงินเป็นอีก 1 ใบเสร็จ) "**

![image](https://user-images.githubusercontent.com/60998712/91527309-c0774c80-e92f-11ea-93e4-4449158646f9.png)

**Comment by satawat-t** [comment]
11. วงเงินแถมโปรโมชั่น (secondary_credit_amount) จะไม่สามารถซื้อสินค้า (type_contract = product) และกลุ่มคอร์ส Botox,Filler  (treatments.for_secondary_credit = 0)

**Comment by satawat-t** [comment]
12. https://www.kkcpos.com/admin/credit-sales-type/15/edit
- ขายวงเงินตัวนี้มูลค่า 20000 บาท ลูกค้าต้องได้วงเงิน 27000 บาท  แต่ระบบให้วงเงินลูกค้าแค่ 20000 บาท
![image](https://user-images.githubusercontent.com/60998712/91684948-155ed100-eb83-11ea-91f9-3a545563711c.png)

table : credit_sale_type
![image](https://user-images.githubusercontent.com/60998712/91685074-71c1f080-eb83-11ea-8539-e93937b02666.png)
