### ISSUE TITLE
หน้าตัดคอร์ส ซ่อนรหัสอนุมัติไม่ให้ User เห็น และ ไม่สามารถตัดคอร์สได้

### ISSUE THREAD

**Issue by satawat-t** [satawat-t/kkc#7]
https://www.kkcpos.com/pos-system/course/cut
- ลูกค้าคนนั้นต้องการตัดใช้งานโดยผ่านเงื่อนไขครับ
![image](https://user-images.githubusercontent.com/60998712/88189601-6d8ce400-cc63-11ea-9a6e-b22b98e213a9.png)
- ทำให้ตรงนี้พิมพ์แล้วไม่เห็นรหัส  เพราะตอนที่อนุมัติ  ออดิตจะ team viewer ไปอนุมัติครับ จะทำให้ User เห็นรหัสครับ
![image](https://user-images.githubusercontent.com/60998712/88189717-8b5a4900-cc63-11ea-8aef-1b5d38bc8760.png)
- เมื่อเข้ามาในหน้าเลือกคอร์สที่จะตัด แสดงผลได้ถูกแล้วครับ
![image](https://user-images.githubusercontent.com/60998712/88189868-bf356e80-cc63-11ea-96d0-a7d414e0cc7d.png)
- แต่ในหน้าตัดคอร์สและให้ค่ามือ ไม่สามารถเลือกจำนวนที่จะตัดได้ครับ
![image](https://user-images.githubusercontent.com/60998712/88189974-e5f3a500-cc63-11ea-8948-69d8e8ffbecf.png)

- แก้ไข text ปุ่ม ตัดคอร์สแบบอิงราคาคอร์ส  เป็น   **ขออนุมัติการตัดคอร์ส**
![image](https://user-images.githubusercontent.com/60998712/88447604-3551f500-ce5f-11ea-83e9-bba74074700c.png)

- และปุ่มอนุมัติการตัดคอร์ส ยังไม่มีในหน้าคอร์สปกติครับ
![image](https://user-images.githubusercontent.com/60998712/88447629-87931600-ce5f-11ea-9499-25146477f34f.png)

**ถ้าเป็นไปได้เก็บรหัสอนุมัติใน DB ได้ไหมครับ เพราะโปรแกรมเมอร์คนเก่าฝังไว้ในโค้ด เผื่อมีการเปลี่ยนรหัสเพื่อความปลอดภัยในอนาคต**

**Comment by kitsupakit45** [comment]
@satawat-t รบกวนพี่เกมส์ ตรวจสอบ issue#7 ด้วยครับ

**Comment by troyzayne** [comment]
kit

**Comment by satawat-t** [comment]
- ใส่รหัสอนุมัติแล้วไม่สามารถตัดคอร์ส Package ได้
https://drive.google.com/file/d/1mxGKFjtMsJO7JVV2xAwpC5giB6VSecvf/view?usp=sharing
