### ISSUE TITLE
รายงานค้างชำระ แสดงชื่อคอร์สที่เป็น Buffet Package Promotion

### ISSUE THREAD

**Issue by satawat-t** [satawat-t/kkc#8]
https://www.kkcpos.com/report/getOverDue/view

table : contracts , courses , sale_payment

- คอร์สที่เป็นกลุ่มคอร์ส บุฟเฟ่ต์ แพคเกจ โปรโมชั่น ให้แสดงแค่ชื่อคอร์สหลักครับ
![image](https://user-images.githubusercontent.com/60998712/88060259-339edd80-cb90-11ea-8aa5-f28ab3b15e30.png)

**Comment by satawat-t** [comment]
- ลูกค้าคนนี้มีคอร์สบุฟเฟ่ต์ KKC Pack 2 เพียงคอร์สเดียว
![image](https://user-images.githubusercontent.com/60998712/88519195-ebfad480-d01b-11ea-8d79-c45864ea4984.png)

- แต่ในรายงานยังแสดงผล KKC Pack 2 หลายรายการครับ และ Export excel ก็แสดงหลายรายการครับ
![image](https://user-images.githubusercontent.com/60998712/88519138-d9809b00-d01b-11ea-9a2c-016e87a20198.png)

**Comment by satawat-t** [comment]
- ออดิตทำการตรวจสอบรายงานแล้วครับ
ตามตัวอย่างรายงานด้านล่าง ต้องมีหัวรายงานด้วยครับ
และยังขาด ยอดรวม ที่ row สุดท้าย
![image](https://user-images.githubusercontent.com/60998712/88761236-ed054080-d198-11ea-8cb4-406206f1ee60.png)

**Comment by satawat-t** [comment]
รายงานค้างชำระ ยังขาดช่อง Filter สาขา   แยกสาขาตาม Branch_id ของ table : courses

**Comment by troyzayne** [comment]
Auditor Passed Stamp
